name: Feature Request
description: Suggest a new tool or output that you would like to see in the pipeline.
title: "[enhancement]: "
labels: ["enhancement"]
projects: ["cchmc/nf-encode-chip"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature for the pipeline!
        Please fill out the following information to help us understand your request.
        The more detail you provide, the better we can understand your needs and prioritize the request.
  - type: input
    id: tool
    attributes:
      label: Tool Name
      description: Provide the name of the tool you would like to see added to the pipeline.
      placeholder: bedtools
    validations:
      required: true
  - type: input
    id: tool_urls
    attributes:
      label: Documentation URL
      description: Provide URLs to documentation / resources for the tools or steps requested.
  - type: textarea
    id: example_usage
    attributes:
      label: Example Usage
      description: Provide an example of how you would use the tool / command.
      render: shell
