channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bioconductor-plyranges=1.26.0
- bioconda::bioconductor-rgreat=2.8.0
- bioconda::bioconductor-rtracklayer=1.66.0
- conda-forge::r-argparse=2.2.5
- conda-forge::r-tidyverse=2.0.0