show_analysis_paths: False
show_analysis_time: False

module_order:
  - fastqc:
      name: "FastQC (raw)"
      info: "This section of the report shows FastQC results before adapter trimming."
      path_filters:
        - "data/fastqc/raw/*.zip"
  - fastqc:
      name: "FastQC (trimmed)"
      info: "This section of the report shows FastQC results after adapter trimming."
      path_filters:
        - "data/fastqc/trimmed/*.zip"
